// VKC Item Clone Naming Tests
// This HeliScript file contains unit tests for clone naming functionality
// Following TDD approach - these tests should initially fail

component CloneNamingTests
{
    Item testObject;
    bool testsPassed = false;
    int testCount = 0;
    int passedCount = 0;
    
    public CloneNamingTests()
    {
        // Test setup - get reference to test object
        testObject = hsItemGet("TestObject");
        RunAllTests();
    }
    
    void RunAllTests()
    {
        hsSystemOutput("Starting Clone Naming Tests...\n");
        
        TestAutoGeneratedNames();
        TestCustomNameAssignment();
        TestNameUniqueness();
        TestSpecialCharacterNames();
        TestEmptyStringName();
        TestLongNameHandling();
        TestNameCollisionHandling();
        
        ReportResults();
    }
    
    void TestAutoGeneratedNames()
    {
        testCount++;
        hsSystemOutput("Test UC-013: Auto Generated Names\n");
        
        if (testObject == null)
        {
            hsSystemOutput("FAIL: Test object not found\n");
            return;
        }
        
        // Create clone without specifying name
        Item clone = hsItemCreateClone(testObject);
        
        if (clone != null)
        {
            string cloneName = clone.GetName();
            
            // Auto-generated name should not be empty
            if (cloneName != "" && cloneName != null)
            {
                hsSystemOutput("PASS: Auto-generated name created: " + cloneName + "\n");
                passedCount++;
            }
            else
            {
                hsSystemOutput("FAIL: Auto-generated name is empty or null\n");
            }
            
            // Cleanup
            hsItemDestroyClone(clone);
        }
        else
        {
            hsSystemOutput("FAIL: Clone creation failed\n");
        }
    }
    
    void TestCustomNameAssignment()
    {
        testCount++;
        hsSystemOutput("Test UC-014: Custom Name Assignment\n");
        
        if (testObject == null)
        {
            hsSystemOutput("FAIL: Test object not found\n");
            return;
        }
        
        string customName = "MyCustomClone_001";
        Item clone = hsItemCreateClone(testObject, customName);
        
        if (clone != null)
        {
            string assignedName = clone.GetName();
            
            if (assignedName == customName)
            {
                hsSystemOutput("PASS: Custom name assigned correctly: " + assignedName + "\n");
                passedCount++;
            }
            else
            {
                hsSystemOutput("FAIL: Custom name not assigned correctly. Expected: " + customName + ", Got: " + assignedName + "\n");
            }
            
            // Cleanup
            hsItemDestroyClone(clone);
        }
        else
        {
            hsSystemOutput("FAIL: Clone creation with custom name failed\n");
        }
    }
    
    void TestNameUniqueness()
    {
        testCount++;
        hsSystemOutput("Test UC-015: Name Uniqueness\n");
        
        if (testObject == null)
        {
            hsSystemOutput("FAIL: Test object not found\n");
            return;
        }
        
        // Create multiple clones and check name uniqueness
        list<Item> clones = [];
        list<string> names = [];
        
        for (int i = 0; i < 5; i++)
        {
            Item clone = hsItemCreateClone(testObject);
            if (clone != null)
            {
                clones.Add(clone);
                names.Add(clone.GetName());
            }
        }
        
        // Check for duplicates
        bool allUnique = true;
        for (int i = 0; i < names.Count(); i++)
        {
            for (int j = i + 1; j < names.Count(); j++)
            {
                if (names[i] == names[j])
                {
                    allUnique = false;
                    break;
                }
            }
            if (!allUnique) break;
        }
        
        if (allUnique && clones.Count() > 1)
        {
            hsSystemOutput("PASS: All auto-generated names are unique\n");
            passedCount++;
        }
        else
        {
            hsSystemOutput("FAIL: Duplicate names detected or insufficient clones created\n");
        }
        
        // Cleanup
        for (int i = 0; i < clones.Count(); i++)
        {
            hsItemDestroyClone(clones[i]);
        }
    }
    
    void TestSpecialCharacterNames()
    {
        testCount++;
        hsSystemOutput("Test UC-016: Special Character Names\n");
        
        if (testObject == null)
        {
            hsSystemOutput("FAIL: Test object not found\n");
            return;
        }
        
        // Test various special character combinations
        list<string> specialNames = [
            "Clone_With_Underscores",
            "Clone-With-Hyphens",
            "Clone.With.Dots",
            "Clone123Numbers",
            "Clone@#$Special",
            "CloneWithSpaces Test",
            "Clone/With/Slashes"
        ];
        
        int successfulNames = 0;
        
        for (int i = 0; i < specialNames.Count(); i++)
        {
            string testName = specialNames[i];
            Item clone = hsItemCreateClone(testObject, testName);
            
            if (clone != null)
            {
                string assignedName = clone.GetName();
                if (assignedName == testName || assignedName != "")
                {
                    successfulNames++;
                    hsSystemOutput("  - Special name handled: " + testName + "\n");
                }
                hsItemDestroyClone(clone);
            }
        }
        
        if (successfulNames > 0)
        {
            hsSystemOutput("PASS: " + successfulNames + "/" + specialNames.Count() + " special character names handled\n");
            passedCount++;
        }
        else
        {
            hsSystemOutput("FAIL: No special character names handled correctly\n");
        }
    }
    
    void TestEmptyStringName()
    {
        testCount++;
        hsSystemOutput("Test UC-017: Empty String Name\n");
        
        if (testObject == null)
        {
            hsSystemOutput("FAIL: Test object not found\n");
            return;
        }
        
        // Test empty string (should behave like no name parameter)
        Item clone = hsItemCreateClone(testObject, "");
        
        if (clone != null)
        {
            string cloneName = clone.GetName();
            
            // Empty string should trigger auto-naming
            if (cloneName != "" && cloneName != null)
            {
                hsSystemOutput("PASS: Empty string handled - auto name generated: " + cloneName + "\n");
                passedCount++;
            }
            else
            {
                hsSystemOutput("FAIL: Empty string not handled correctly\n");
            }
            
            // Cleanup
            hsItemDestroyClone(clone);
        }
        else
        {
            hsSystemOutput("FAIL: Clone creation with empty string failed\n");
        }
    }
    
    void TestLongNameHandling()
    {
        testCount++;
        hsSystemOutput("Test UC-018: Long Name Handling\n");
        
        if (testObject == null)
        {
            hsSystemOutput("FAIL: Test object not found\n");
            return;
        }
        
        // Create a very long name
        string longName = "ThisIsAVeryLongCloneNameThatExceedsNormalLengthLimitsAndShouldBeHandledGracefullyByTheSystem123456789";
        Item clone = hsItemCreateClone(testObject, longName);
        
        if (clone != null)
        {
            string assignedName = clone.GetName();
            
            // Should either accept the long name or truncate it gracefully
            if (assignedName != "" && assignedName != null)
            {
                hsSystemOutput("PASS: Long name handled - result: " + assignedName + "\n");
                passedCount++;
            }
            else
            {
                hsSystemOutput("FAIL: Long name not handled correctly\n");
            }
            
            // Cleanup
            hsItemDestroyClone(clone);
        }
        else
        {
            hsSystemOutput("FAIL: Clone creation with long name failed\n");
        }
    }
    
    void TestNameCollisionHandling()
    {
        testCount++;
        hsSystemOutput("Test UC-019: Name Collision Handling\n");
        
        if (testObject == null)
        {
            hsSystemOutput("FAIL: Test object not found\n");
            return;
        }
        
        string baseName = "CollisionTest";
        
        // Create first clone with specific name
        Item clone1 = hsItemCreateClone(testObject, baseName);
        
        if (clone1 == null)
        {
            hsSystemOutput("FAIL: Could not create first clone\n");
            return;
        }
        
        // Try to create second clone with same name
        Item clone2 = hsItemCreateClone(testObject, baseName);
        
        bool handledCollision = false;
        
        if (clone2 != null)
        {
            string name1 = clone1.GetName();
            string name2 = clone2.GetName();
            
            // Names should be different to handle collision
            if (name1 != name2)
            {
                handledCollision = true;
                hsSystemOutput("PASS: Name collision handled - Clone1: " + name1 + ", Clone2: " + name2 + "\n");
            }
            
            // Cleanup
            hsItemDestroyClone(clone2);
        }
        
        // Cleanup first clone
        hsItemDestroyClone(clone1);
        
        if (handledCollision)
        {
            passedCount++;
        }
        else
        {
            hsSystemOutput("FAIL: Name collision not handled properly\n");
        }
    }
    
    void ReportResults()
    {
        hsSystemOutput("=== Clone Naming Test Results ===\n");
        hsSystemOutput("Total Tests: " + testCount + "\n");
        hsSystemOutput("Passed: " + passedCount + "\n");
        hsSystemOutput("Failed: " + (testCount - passedCount) + "\n");
        
        float successRate = (float)passedCount / testCount * 100.0f;
        hsSystemOutput("Success Rate: " + successRate + "%\n");
        
        testsPassed = (passedCount == testCount);
        
        if (testsPassed)
        {
            hsSystemOutput("=== ALL CLONE NAMING TESTS PASSED ===\n");
        }
        else
        {
            hsSystemOutput("=== SOME CLONE NAMING TESTS FAILED ===\n");
        }
    }
}